### ISSUE TITLE
Error: Targeted directory 'assets/a/a' is empty.

### ISSUE THREAD

**Issue by farzan3** [actions-on-google/appactions-fitness-kotlin#10]
Hello, i am getting this error , help me thanks

Platform Windows 

```
C:\Users\ALI FARZAN\Desktop\lemo>java -jar bundletool.jar build-apks --connected-device --bundle=lemogame_debug.aab --output=op.apks
INFO: The APKs will be signed with the debug keystore found at 'C:\Users\ALI FARZAN\.android\debug.keystore'.
[BT:0.10.2] Error: Targeted directory 'assets/a/a' is empty.
com.android.tools.build.bundletool.model.exceptions.ValidationException: Targeted directory 'assets/a/a' is empty.
        at com.android.tools.build.bundletool.model.exceptions.ValidationException$Builder.build(ValidationException.java:49)
        at com.android.tools.build.bundletool.model.exceptions.ValidationException$Builder.build(ValidationException.java:41)
        at com.android.tools.build.bundletool.validation.AssetsTargetingValidator.validateTargeting(AssetsTargetingValidator.java:54)
        at com.android.tools.build.bundletool.validation.AssetsTargetingValidator.lambda$validateModule$0(AssetsTargetingValidator.java:35)
        at java.util.Optional.ifPresent(Optional.java:159)
        at com.android.tools.build.bundletool.validation.AssetsTargetingValidator.validateModule(AssetsTargetingValidator.java:35)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleModulesUsingSubValidator(ValidatorRunner.java:78)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundleUsingSubValidator(ValidatorRunner.java:69)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.lambda$validateBundle$3(ValidatorRunner.java:58)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
        at com.android.tools.build.bundletool.validation.ValidatorRunner.validateBundle(ValidatorRunner.java:58)
        at com.android.tools.build.bundletool.validation.AppBundleValidator.validate(AppBundleValidator.java:75)
        at com.android.tools.build.bundletool.commands.BuildApksManager.executeWithZip(BuildApksManager.java:131)
        at com.android.tools.build.bundletool.commands.BuildApksManager.execute(BuildApksManager.java:110)
        at com.android.tools.build.bundletool.commands.BuildApksCommand.execute(BuildApksCommand.java:524)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
```

**Comment by skimarxall** [comment]
This does not look like something related to app actions or this sample.

Please provide more information
